name: Deployment Activity

on: push
#on: [push, workflow_dispatch]
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'src/**'
#  workflow_dispatch:
#on:
#  push:
#  pull_request:
#    types: [opened, closed]
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, world!"

      - name: Get code (this might be redundant as you've checked out the code above)
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures that the test job runs only after build completes
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures that the deploy job runs only after test completes
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying the application..."


#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node: [ 14, 16, 18 ]
#    name: Node ${{ matrix.node }} sample
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup node
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node }}
#      - run: npm ci